### ISSUE TITLE
Code In Swift 

### ISSUE THREAD

**Issue by ghost** [intOrfloat/spotitySpeedExtension#2]
Hello IntOrFloat, 
I am using your [SpotifySpeedExtesnion](https://github.com/intOrfloat/spotitySpeedExtension). This is really amazing. if you don't  mind Could you advice me how to handling this code in swift language. Because i m also create a demo which change Spotify Song Speed but i don't know how?. So please advice me how to handle this code in swift language. Thank you.

**Comment by intOrfloat** [comment]
i believe you'd need to use spotify's outdated(2014) sdk https://github.com/spotify/ios-streaming-sdk here and hope it continues working. specifically i'd recommend looking through their past commits to see what where they added and removed the feature here https://github.com/spotify/ios-streaming-sdk/commits/master

**Comment by ghost** [comment]
@intOrfloat,

Thank you for your reply. but in this  SDK no one option to set and get playback speed. please suggest me what i can do for change playback speed of Spotify Song.
